// src/pages/reporting/PipShell.tsx
import { MemoryRouter } from 'react-router-dom'
import { Toaster } from 'sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import ReportingPage from './ReportingPage'

export default function PipShell() {
  return (
    <MemoryRouter>
      <TooltipProvider>
        <Toaster richColors position="top-right" />
        <div className="pip-shell min-h-full bg-background">
          <ReportingPage pipMode />
        </div>
      </TooltipProvider>
    </MemoryRouter>
  )
}

// src/pages/reporting/PipShell.vue
<template>
  <TooltipProvider>
    <Toaster />
    <div class="pip-shell min-h-full bg-background">
      <ReportingPage />
    </div>
  </TooltipProvider>
</template>

<script setup lang="ts">
import { provide } from 'vue'
import ReportingPage from './ReportingPage.vue'
import Toaster from '@/components/ui/toaster.vue'
import TooltipProvider from '@/components/ui/TooltipProvider.vue'

provide('pipMode', true)
</script>
