// src/App.tsx
import { Toaster } from 'sonner'
import { RouterProvider } from 'react-router-dom'
import { TooltipProvider } from '@radix-ui/react-tooltip'
import { router } from '@/router'

export default function App() {
  return (
    <TooltipProvider>
      <RouterProvider router={router} />
      <Toaster richColors position="top-right" />
    </TooltipProvider>
  )
}

// src/App.vue
<template>
  <div id="app">
    <Toaster />
    <TooltipProvider>
      <RouterView />
    </TooltipProvider>
  </div>
</template>

<script setup lang="ts">
import { RouterView } from 'vue-router'
import Toaster from '@/components/ui/toaster.vue'
import TooltipProvider from '@/components/ui/TooltipProvider.vue'
</script>
