// src/pages/admin/UserManagementPage.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Plus, Edit2, Calendar, Clock, CalendarClock, Shield, Search } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { mockPhysicians } from "@/data/mockData";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import type { UserRole, Physician } from "@/types/study";

const roleLabels: Record<UserRole, string> = {
  admin: "Admin",
  "reporting-radiologist": "Reporting",
  "validating-radiologist": "Validating",
};

const roleBadgeColors: Record<UserRole, string> = {
  admin: "bg-destructive/10 text-destructive border-destructive/20",
  "reporting-radiologist": "bg-primary/10 text-primary border-primary/20",
  "validating-radiologist": "bg-status-finalized/10 text-status-finalized border-status-finalized/20",
};

export function UserManagementPage() {
  const navigate = useNavigate();
  const [selectedPhysician, setSelectedPhysician] = useState<string | null>(null);
  const [physicians, setPhysicians] = useState<Physician[]>(mockPhysicians);
  const [searchQuery, setSearchQuery] = useState("");

  const filteredPhysicians = physicians.filter(p => {
    const query = searchQuery.toLowerCase();
    return p.fullName.toLowerCase().includes(query) || p.id.toLowerCase().includes(query);
  });

  const selected = physicians.find(p => p.id === selectedPhysician);

  const handleRoleChange = (physicianId: string, newRole: UserRole) => {
    setPhysicians(prev => 
      prev.map(p => p.id === physicianId ? { ...p, role: newRole } : p)
    );
  };

  const openSchedule = (physicianId: string) => {
    navigate(`/schedule/${physicianId}`);
  };

  return (
    <div>
      <PageHeader
        title="User Management"
        subtitle="Manage physicians and their assignments"
        actions={
          <Button>
            <Plus className="w-4 h-4 mr-2" />
            Add Physician
          </Button>
        }
      />

      <div className="grid grid-cols-3 gap-6">
        {/* Physician List */}
        <div className="col-span-2">
          <div className="clinical-card overflow-hidden">
            {/* Search Filter */}
            <div className="p-4 border-b border-border">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Search by name or ID..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-9"
                />
              </div>
            </div>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Physician</th>
                  <th>Role</th>
                  <th>Contact</th>
                  <th>Modalities</th>
                  <th>Workload</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {filteredPhysicians.map((physician) => (
                  <tr 
                    key={physician.id}
                    className={cn(
                      "cursor-pointer",
                      selectedPhysician === physician.id && "bg-accent"
                    )}
                    onClick={() => setSelectedPhysician(physician.id)}
                  >
                    <td>
                      <div className="font-medium text-sm">{physician.fullName}</div>
                      <div className="text-xs text-muted-foreground">
                        {physician.statistics.total.toLocaleString()} studies completed
                      </div>
                    </td>
                    <td onClick={(e) => e.stopPropagation()}>
                      <Select 
                        value={physician.role} 
                        onValueChange={(value: UserRole) => handleRoleChange(physician.id, value)}
                      >
                        <SelectTrigger className={cn(
                          "w-[130px] h-8 text-xs border",
                          roleBadgeColors[physician.role]
                        )}>
                          <Shield className="w-3 h-3 mr-1" />
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="admin">
                            <div className="flex items-center gap-2">
                              <div className="w-2 h-2 rounded-full bg-destructive" />
                              Admin
                            </div>
                          </SelectItem>
                          <SelectItem value="reporting-radiologist">
                            <div className="flex items-center gap-2">
                              <div className="w-2 h-2 rounded-full bg-primary" />
                              Reporting
                            </div>
                          </SelectItem>
                          <SelectItem value="validating-radiologist">
                            <div className="flex items-center gap-2">
                              <div className="w-2 h-2 rounded-full bg-status-finalized" />
                              Validating
                            </div>
                          </SelectItem>
                        </SelectContent>
                      </Select>
                    </td>
                    <td>
                      <div className="text-sm">{physician.phone}</div>
                      {physician.telegram && (
                        <div className="text-xs text-muted-foreground">{physician.telegram}</div>
                      )}
                    </td>
                    <td>
                      <div className="flex flex-wrap gap-1">
                        {physician.supportedModalities.map((m) => (
                          <Badge key={m} variant="secondary" className="text-xs">{m}</Badge>
                        ))}
                      </div>
                    </td>
                    <td>
                      <div className="flex items-center gap-2">
                        <div className={cn(
                          "text-sm font-medium",
                          physician.activeStudies >= physician.maxActiveStudies && "text-destructive"
                        )}>
                          {physician.activeStudies}/{physician.maxActiveStudies}
                        </div>
                        <div className="w-16 h-2 bg-muted rounded-full overflow-hidden">
                          <div 
                            className={cn(
                              "h-full transition-all",
                              physician.activeStudies >= physician.maxActiveStudies 
                                ? "bg-destructive" 
                                : "bg-primary"
                            )}
                            style={{ width: `${(physician.activeStudies / physician.maxActiveStudies) * 100}%` }}
                          />
                        </div>
                      </div>
                    </td>
                    <td>
                      <div className="flex items-center gap-1">
                        <Button 
                          variant="ghost" 
                          size="icon" 
                          className="h-8 w-8"
                          onClick={(e) => {
                            e.stopPropagation();
                            openSchedule(physician.id);
                          }}
                          title="Manage Schedule"
                        >
                          <CalendarClock className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8">
                          <Edit2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Physician Details Panel */}
        <div className="col-span-1">
          {selected ? (
            <div className="clinical-card">
              <div className="clinical-card-header">
                <h3 className="text-sm font-semibold">{selected.fullName}</h3>
                <Badge 
                  variant="outline" 
                  className={cn("text-xs", roleBadgeColors[selected.role])}
                >
                  {roleLabels[selected.role]}
                </Badge>
              </div>
              <div className="clinical-card-body space-y-4">
                {/* Schedule */}
                <div>
                  <div className="flex items-center justify-between">
                    <h4 className="section-header">Default Schedule</h4>
                    <Button 
                      variant="ghost" 
                      size="sm" 
                      className="h-7 text-xs"
                      onClick={() => openSchedule(selected.id)}
                    >
                      <CalendarClock className="w-3 h-3 mr-1" />
                      Manage
                    </Button>
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-sm">
                      <Calendar className="w-4 h-4 text-muted-foreground" />
                      <span>{selected.schedule.days.join(", ")}</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                      <Clock className="w-4 h-4 text-muted-foreground" />
                      <span>{selected.schedule.hours.start} - {selected.schedule.hours.end}</span>
                    </div>
                  </div>
                </div>

                {/* Body Areas */}
                <div>
                  <h4 className="section-header">Body Areas</h4>
                  <div className="flex flex-wrap gap-1">
                    {selected.supportedBodyAreas.map((area) => (
                      <Badge key={area} variant="outline" className="text-xs">{area}</Badge>
                    ))}
                  </div>
                </div>

                {/* Statistics */}
                <div>
                  <h4 className="section-header">Statistics by Modality</h4>
                  <div className="space-y-2">
                    {Object.entries(selected.statistics.byModality)
                      .filter(([_, count]) => count > 0)
                      .sort(([, a], [, b]) => b - a)
                      .map(([modality, count]) => (
                        <div key={modality} className="flex items-center justify-between text-sm">
                          <span>{modality}</span>
                          <span className="font-medium">{count.toLocaleString()}</span>
                        </div>
                      ))}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="clinical-card p-8 text-center text-muted-foreground">
              <p className="text-sm">Select a physician to view details</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/pages/admin/UserManagementPage.vue
<template>
  <div>
    <PageHeader
      title="User Management"
      subtitle="Manage physicians and their assignments"
    >
      <template #actions>
        <Button>
          <Plus class="w-4 h-4 mr-2" />
          Add Physician
        </Button>
      </template>
    </PageHeader>

    <div class="grid grid-cols-3 gap-6">
      <!-- Physician List -->
      <div class="col-span-2">
        <div class="clinical-card overflow-hidden">
          <!-- Search Filter -->
          <div class="p-4 border-b border-border">
            <div class="relative">
              <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search by name or ID..."
                :model-value="searchQuery"
                @update:model-value="searchQuery = $event"
                class="pl-9"
              />
            </div>
          </div>
          <table class="data-table">
            <thead>
              <tr>
                <th>Physician</th>
                <th>Role</th>
                <th>Contact</th>
                <th>Modalities</th>
                <th>Workload</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="physician in filteredPhysicians"
                :key="physician.id"
                :class="cn(
                  'cursor-pointer',
                  selectedPhysician === physician.id && 'bg-accent'
                )"
                @click="selectedPhysician = physician.id"
              >
                <td>
                  <div class="font-medium text-sm">{{ physician.fullName }}</div>
                  <div class="text-xs text-muted-foreground">
                    {{ physician.statistics.total.toLocaleString() }} studies completed
                  </div>
                </td>
                <td @click.stop>
                  <Select
                    :model-value="physician.role"
                    @update:model-value="handleRoleChange(physician.id, $event as UserRole)"
                  >
                    <SelectTrigger :class="cn(
                      'w-[130px] h-8 text-xs border',
                      roleBadgeColors[physician.role]
                    )">
                      <Shield class="w-3 h-3 mr-1" />
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="admin">
                        <div class="flex items-center gap-2">
                          <div class="w-2 h-2 rounded-full bg-destructive" />
                          Admin
                        </div>
                      </SelectItem>
                      <SelectItem value="reporting-radiologist">
                        <div class="flex items-center gap-2">
                          <div class="w-2 h-2 rounded-full bg-primary" />
                          Reporting
                        </div>
                      </SelectItem>
                      <SelectItem value="validating-radiologist">
                        <div class="flex items-center gap-2">
                          <div class="w-2 h-2 rounded-full bg-status-finalized" />
                          Validating
                        </div>
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </td>
                <td>
                  <div class="text-sm">{{ physician.phone }}</div>
                  <div v-if="physician.telegram" class="text-xs text-muted-foreground">{{ physician.telegram }}</div>
                </td>
                <td>
                  <div class="flex flex-wrap gap-1">
                    <Badge v-for="m in physician.supportedModalities" :key="m" variant="secondary" class="text-xs">{{ m }}</Badge>
                  </div>
                </td>
                <td>
                  <div class="flex items-center gap-2">
                    <div :class="cn(
                      'text-sm font-medium',
                      physician.activeStudies >= physician.maxActiveStudies && 'text-destructive'
                    )">
                      {{ physician.activeStudies }}/{{ physician.maxActiveStudies }}
                    </div>
                    <div class="w-16 h-2 bg-muted rounded-full overflow-hidden">
                      <div
                        :class="cn(
                          'h-full transition-all',
                          physician.activeStudies >= physician.maxActiveStudies
                            ? 'bg-destructive'
                            : 'bg-primary'
                        )"
                        :style="{ width: `${(physician.activeStudies / physician.maxActiveStudies) * 100}%` }"
                      />
                    </div>
                  </div>
                </td>
                <td @click.stop>
                  <div class="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="icon"
                      class="h-8 w-8"
                      @click="openSchedule(physician.id)"
                      title="Manage Schedule"
                    >
                      <CalendarClock class="w-4 h-4" />
                    </Button>
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      class="h-8 w-8"
                      @click="handleEdit(physician.id)"
                      title="Edit Physician"
                    >
                      <Edit2 class="w-4 h-4" />
                    </Button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Physician Details Panel -->
      <div class="col-span-1">
        <div v-if="selected" class="clinical-card">
          <div class="clinical-card-header">
            <h3 class="text-sm font-semibold">{{ selected.fullName }}</h3>
            <Badge
              variant="outline"
              :class="cn('text-xs', roleBadgeColors[selected.role])"
            >
              {{ roleLabels[selected.role] }}
            </Badge>
          </div>
          <div class="clinical-card-body space-y-4">
            <!-- Schedule -->
            <div>
              <div class="flex items-center justify-between">
                <h4 class="section-header">Default Schedule</h4>
                <Button
                  variant="ghost"
                  size="sm"
                  class="h-7 text-xs"
                  @click="openSchedule(selected.id)"
                >
                  <CalendarClock class="w-3 h-3 mr-1" />
                  Manage
                </Button>
              </div>
              <div class="space-y-2">
                <div class="flex items-center gap-2 text-sm">
                  <Calendar class="w-4 h-4 text-muted-foreground" />
                  <span>{{ selected.schedule.days.join(", ") }}</span>
                </div>
                <div class="flex items-center gap-2 text-sm">
                  <Clock class="w-4 h-4 text-muted-foreground" />
                  <span>{{ selected.schedule.hours.start }} - {{ selected.schedule.hours.end }}</span>
                </div>
              </div>
            </div>

            <!-- Body Areas -->
            <div>
              <h4 class="section-header">Body Areas</h4>
              <div class="flex flex-wrap gap-1">
                <Badge v-for="area in selected.supportedBodyAreas" :key="area" variant="outline" class="text-xs">{{ area }}</Badge>
              </div>
            </div>

            <!-- Statistics -->
            <div>
              <h4 class="section-header">Statistics by Modality</h4>
              <div class="space-y-2">
                <div
                  v-for="[modality, count] in Object.entries(selected.statistics.byModality)
                    .filter(([_, count]) => count > 0)
                    .sort(([, a], [, b]) => (b as number) - (a as number))"
                  :key="modality"
                  class="flex items-center justify-between text-sm"
                >
                  <span>{{ modality }}</span>
                  <span class="font-medium">{{ (count as number).toLocaleString() }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div v-else class="clinical-card p-8 text-center text-muted-foreground">
          <p class="text-sm">Select a physician to view details</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Plus, Edit2, Calendar, Clock, CalendarClock, Shield, Search } from 'lucide-vue-next'
import PageHeader from '@/components/layout/PageHeader.vue'
import Button from '@/components/ui/button.vue'
import Input from '@/components/ui/input.vue'
import { mockPhysicians } from '@/data/mockData'
import Badge from '@/components/ui/badge.vue'
import Select from '@/components/ui/select.vue'
import SelectTrigger from '@/components/ui/SelectTrigger.vue'
import SelectContent from '@/components/ui/SelectContent.vue'
import SelectValue from '@/components/ui/SelectValue.vue'
import SelectItem from '@/components/ui/SelectItem.vue'
import { cn } from '@/lib/utils'
import type { UserRole, Physician } from '@/types/study'

const router = useRouter()

const roleLabels: Record<UserRole, string> = {
  admin: "Admin",
  "reporting-radiologist": "Reporting",
  "validating-radiologist": "Validating",
}

const roleBadgeColors: Record<UserRole, string> = {
  admin: "bg-destructive/10 text-destructive border-destructive/20",
  "reporting-radiologist": "bg-primary/10 text-primary border-primary/20",
  "validating-radiologist": "bg-status-finalized/10 text-status-finalized border-status-finalized/20",
}

const selectedPhysician = ref<string | null>(null)
const physicians = ref<Physician[]>(mockPhysicians)
const searchQuery = ref("")

const filteredPhysicians = computed(() => {
  const query = searchQuery.value.toLowerCase()
  return physicians.value.filter(p =>
    p.fullName.toLowerCase().includes(query) || p.id.toLowerCase().includes(query)
  )
})

const selected = computed(() =>
  physicians.value.find(p => p.id === selectedPhysician.value)
)

const handleRoleChange = (physicianId: string, newRole: UserRole) => {
  physicians.value = physicians.value.map(p =>
    p.id === physicianId ? { ...p, role: newRole } : p
  )
}

const openSchedule = (physicianId: string) => {
  router.push(`/schedule/${physicianId}`)
}

const handleEdit = (physicianId: string) => {
  // TODO: Implement edit physician functionality
  console.log('Edit physician:', physicianId)
  // This could open a dialog or navigate to an edit page
}
</script>
