// src/components/ui/LinkedBodyAreasDisplay.vue
<template>
  <div>
    <div class="flex items-center gap-2">
      <span class="text-sm font-medium">{{ study.modality }}</span>
      <span class="text-sm font-semibold text-foreground">{{ study.bodyArea }}</span>
    </div>
    <div v-if="isMultiZone" class="text-xs text-primary font-medium flex items-center gap-1">
      <Link2 class="w-3 h-3" />
      <span>+ {{ otherBodyAreas.join(', ') }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Link2 } from 'lucide-vue-next'
import type { Study } from '@/types/study'

interface Props {
  study: Study
  allStudies: Study[]
  showBadge?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  showBadge: true
})

const linkedStudies = computed(() => {
  return props.study.linkedStudyGroup 
    ? props.allStudies.filter(s => s.linkedStudyGroup === props.study.linkedStudyGroup && s.id !== props.study.id)
    : []
})

const isMultiZone = computed(() => linkedStudies.value.length > 0)
const otherBodyAreas = computed(() => linkedStudies.value.map(s => s.bodyArea))
</script>

// src/components/ui/LinkedBodyAreasDisplay.tsx
import { Link2 } from 'lucide-react'
import type { Study } from '@/types/study'

interface Props {
  study: Study
  allStudies: Study[]
}

export function LinkedBodyAreasDisplay({ study, allStudies }: Props) {
  const linkedStudies = study.linkedStudyGroup
    ? allStudies.filter(s => s.linkedStudyGroup === study.linkedStudyGroup && s.id !== study.id)
    : []

  const isMultiZone = linkedStudies.length > 0
  const otherBodyAreas = linkedStudies.map(s => s.bodyArea)

  return (
    <div>
      <div className="flex items-center gap-2">
        <span className="text-sm font-medium">{study.modality}</span>
        <span className="text-sm font-semibold text-foreground">{study.bodyArea}</span>
      </div>
      {isMultiZone && (
        <div className="text-xs text-primary font-medium flex items-center gap-1">
          <Link2 className="w-3 h-3" />
          <span>+ {otherBodyAreas.join(', ')}</span>
        </div>
      )}
    </div>
  )
}
